RMM_Euler_V1: RMM_Euler_V1.o alg_graphs.o
	g++ -o RMM_Euler_V1 RMM_Euler_V1.o alg_graphs.o

RMM_Euler_V1.o: RMM_Euler_V1.cpp alg_graphs.h
	g++ -c RMM_Euler_V1.cpp




all: RMM_Euler_V1

clean:
	rm -f RMM_Euler_V1 RMM_Euler_V1.o alg_graphs.o